### ISSUE TITLE
Versioning is confusing and there are no recent tags

### ISSUE THREAD

**Issue by jean-christophe-manciot** [CumulusNetworks/quagga#17]
@ddutt 
First off, it is unclear whether Cumulus has completely taken over Quagga development, or if this is just a fork. I must have missed the related news. 
- In the first case, why is there a different URL for Quagga? 
- In the latter case, why do you name the packages with the same name "quagga"?

Back to main topic of this thread:
- Cumulus has removed all recent tags, so we don't know where are the stable/unstable releases. Adding some tags would really help follow your development status.
- after building a deb from the last commit f6da66a913bcae1d3f75c55f24e72e97288af619, the release number is "**0.99.23.1-1+cl3u2**". However, the last tag from the original Quagga sources points to "**1.0.20160315**", which means that the cumulus quagga packages can never automatically update the original quagga packages.

There are 2 solutions:
- either change the packages base name
- or realign your versioning with original sources to something like **1.0.\<date\>**

I intend to build, use and advertise your package on my own **[public PPA](https://gitlab.com/jean-christophe-manciot/ppa)** along with many others.

**Comment by jean-christophe-manciot** [comment]
Also, the tags could be in the form "**quagga-\<version\>**".

**Comment by donaldsharp** [comment]
We are using 0.99.23.1-1+cl3u2 because that is the version that our quagga is based off of.  We are working towards bringing it more up to date.

**Comment by AdrianSimionov** [comment]
Unfortunately Quagga is another project which will die because of a commercial approach, Jean Christophe. Compared to other open source project it is very complicated to submit code to quagga (only via email to their maintainer). Cumulus keeps this GitHub project only to cover their legal aspect of open source in my opinion, but the answer "we are working towards bringing it more up to date" is the same since Cumulus took over Quagga. They are not interested in submitting every patch here also because it will compete with their own product.

There are some spin offs from Quagga (due to a complicated code contributing approach) but the direction is clear.

Good job Cumulus.

**Comment by donaldsharp** [comment]
what are you talking about?  The repository is up to date w/ 3.0 release of cumulus Quagga.  We've recently released a 3.1 version which I haven't pushed yet.  I've just been busy.  I'll push it in a few minutes here.

I do agree though that upstream it is nearly impossible to submit anything.  The current maintainer has his way that he wants to work.

**Comment by donaldsharp** [comment]
Additionally if you have something you would like to contribute here, feel free to give a pull request and I'll take it.

**Comment by k0ste** [comment]
> They are not interested in submitting every patch here also because it will compete with their own product.

The Cumulus, probably the only company that provides each patch. Visit [OSS](http://oss.cumulusnetworks.com/) repository.
Thanks, Cumulus for this.

**Comment by jean-christophe-manciot** [comment]
Thanks @AdrianSimionov for your comment which somehow helped @donaldsharp find a few minutes to push 4 months of code.
Nice work guys ;)
Maybe @donaldsharp can find a few more minutes to tag his team's work to a updated release allowing semi-automatic upgrades from package managers:
```
git describe --abbrev=0 --tags
quagga-0.99.22
```

**Comment by AdrianSimionov** [comment]
Donald I apologize if my comment was a bit direct, my intention was not to offend anyone. I am just a bit frustrated regarding a project with such an amazing potential.

1-2 years ago I was looking for a project to contribute to and after some research I ended up with 2 options: wireshark and quagga. Both projects are incorporated into a comercial product, mature products, both used in many deployments and I was very interested on both.

I ended up pushing code to wireshark just because of the approach they take on new developers, on how open and automated everything is, I consider Cumulus can do a lot more for the community. And welcoming new developers will benefit everyone.

Wireshark has also a copy in GitHub but every cherry-pick from gerrit instantly goes into GitHub.

**Comment by donaldsharp** [comment]
Adrian -

I'm sorry you felt stymied about contributing to Quagga. 

All - If you are interested in contributing feel free to contact me and I will help you get up and running.

**Comment by k0ste** [comment]
> Thanks @AdrianSimionov for your comment which somehow helped @donaldsharp find a few minutes to push 4 months of code.

I know that Cumulus use Bitbucket. For automatically pushing code to mirror (i.e. github) you can install free add-on [Repository Mirror Plugin for Bitbucket](https://marketplace.atlassian.com/plugins/com.englishtown.stash-hook-mirror/server/overview).

**Comment by jean-christophe-manciot** [comment]
Would it be fair to tag the last commit as **CumulusNetworks/3.2.0**?
